apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: bouncer
  name: bouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bouncer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: bouncer
    spec:
      containers:
        - env:
            - name: ADMIN_USERS
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_USERS
                  name: env-bouncer
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: env-bouncer
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: env-bouncer
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: env-bouncer
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: env-bouncer
            - name: GET_HOSTS_FROM
              valueFrom:
                configMapKeyRef:
                  key: GET_HOSTS_FROM
                  name: env-bouncer
            - name: POOL_MODE
              valueFrom:
                configMapKeyRef:
                  key: POOL_MODE
                  name: env-bouncer
          image: edoburu/pgbouncer
          name: bouncer
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
