version: "3"
services:
  postgres-db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    env_file: .env-postgres
  
  bouncer:
    image: edoburu/pgbouncer
    restart: always
    env_file: .env-bouncer
    ports:
      - "5432:5432"
    depends_on:
      postgres-db:
        condition: service_started
  
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: on-failure
    env_file: .env-app
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_started
      bouncer:
        condition: service_started
      rabbitmq:
        condition: service_started
  
  consumer:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    restart: on-failure
    env_file: .env-consumer
    ports:
      - "8081:8080"
    depends_on:
      postgres-db:
        condition: service_started
      bouncer:
        condition: service_started
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always