version: "3"
services:
  postgres-db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    env_file: .env-postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    labels:
      kompose.service.type: NodePort